### PR TITLE
Word Counts Fixes

### PR DESCRIPTION
**Pull request by janzaheer**

### CODE REVIEW

**Comment by enoren5** [comment]
Jaheer on Upwork says: 

> I have a created a function, actually a hack that counts the words in utils.py. It will count the word of a string. in the landing page I am showing the words count from posts model. pagination is also done.
> 
> For Alice.txt, just read the file first, and pass the content in the function words_count(content) that i created in utils.py. The functionality itself returns the dictionary of the words. e.g  {'she': 18, 'to': 18, 'the': 17, 'it': 14, 'and': 13, 'was': 10, 'a': 10, 'of': 9, 'her': 8, 'down': 7, 'for': 5, 'that': 5}

**Comment by enoren5** [comment]
Here is my response:

Thank you for your hard work so far. I’ve seen your diffs. They look great. 

Although you went to the trouble of rewriting the `views.py` and creating a new `utils.py`. I am not quite sure that was necessary because if you checkout to the original master branch (prior to your PR) and change one line by adding `‘counters/’` to the first argument inside the urlpatterns path inside the `counters/urls.py`, then when a web visitor navigates to `http://localhost:8000/counters`, the table appears with the correct output (top 10 most common words in Alice.txt). So this indicates that my existing function inside my current master `counters/views.py` works and that the problem is actually a routing issue.  Would you be able to correct this routing issue so that the table shows the output on the landing page at `http://localhost:8000/` instead of `http://localhost:8000/counters/`.

After making that change to `counters/urls.py`, here is the change on my webserver: https://f30f4db1bad4.ngrok.io/counters for you to take a look at.

As nice as it is to see your own dictionary implementation of the word counter feature, it is a bit of an unexpected surprise. The pagination feature is also interesting but it’s not part of the two issues so it is a bit of a surprise to me as well.

**Comment by janzaheer** [comment]
I have a Question,
Why you are using nltk package to count the words?

And you want me to use your code for the posts page right? Do I only display the word count of Alice.txt in posts page, and what about the posts content should i also count the post word?

**Comment by enoren5** [comment]
> Why you are using nltk package to count the words?

The advantage with using the Natural Language Tool Kit is that it will filter out common english words such as "she", "the", "to" and "it" and instead show other commonly appearing and more interesting words such as "alice", "little", "queen"

> And you want me to use your code for the posts page right? Do I only display the word count of Alice.txt in posts page, and what about the posts content should I also count the post words?

Hmmm, I think I see what you mean: There might a bit of confusion as to which text content to show as counted on the posts page. Like, should the table process `Alice.txt` text? Or should it process the `posts` content entered by the Admin User? If this is the problem you are pointing towards, then I'm thinking that perhaps a good solution would be to add a second HTML table to when the web visitors views the landing page. So could you make sure there are two tables on the home page, one counting the words for Alice.txt and the other for counting post content?

**Comment by janzaheer** [comment]
Got it, Thanks,
Will do the changes

**Comment by janzaheer** [comment]
Check the new commit, I am using your code for words count,
moved your code into utils to avoid repeatition. This is a good approach to write a code.
I suggest you to always write class based views in djange.

**Pull request merged**
