### PR TITLE
Re-positioned Redactors Box

### PR DESCRIPTION
**Pull request by UmarGit**
- [X] #17 Re-positioned Redactors Box by styling css of `post-counts` as:

`clear: right`

> And moving the `card-processors` div into `post-content` div.

### CODE REVIEW

**Comment by enoren5** [comment]
Hi Umar! The changes accomplish Issue #17. Thank you. Before I merge these changes into my master branch, I have one further question: I see that you moved the `card-processor` class code block down to below the `post-content` class. But did you change anything else within the `card-processor` code block? It's hard for me to tell.

**Comment by UmarGit** [comment]
@enoren5 yes css styling.

**Comment by enoren5** [comment]
Yes, I noticed the line change in the CSS. But did you change anything else in the `landings.html` template?

**Comment by UmarGit** [comment]
no nothing

**Pull request merged**
